import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "./components/header/Navbar";
import Footer from "./components/header/Footer";
import { Suspense } from "react";

const notoserifbengali = Noto_Serif_Bengali({
  subsets: ["bengali"],
  variable: "--font-noto-serif-bengali",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="
      En"
      className={`${notoserifbengali.variable} h-full antialiased`}
    >
      <body className="min-h-full flex  flex-col">

        <Suspense fallback='loading'>
          <Navbar />
          <main className="container max-w-6xl mx-auto">
            {children}

          </main>
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}
